# SCREEN
SCREEN_TITLE = "Agar.ai"
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000
FULLSCREEN = False
SCREEN_PART_WIDTH = 50

PLAYER_START_SPEED = (3, 5)  # Between
PLAYERS = 2000
PLAYER_START_SCORE = (1, 3)  # Between
MAX_SCORE = 100
MULTI_FAC = 0.3  # Multiply factor

UPDATE_TICKS = 20